spring:
  application:
    name: kotlin-sample-api
  profiles:
    group:
      local:
        - core-local
        - api-local
      dev:
        - core-dev
        - api-dev
      prod:
        - core-prod
        - api-prod

